### PR TITLE
ci: add basic testing

### PR DESCRIPTION
**Pull request by Borda**
to ensure reproducibility and allow any future contributions

### CODE REVIEW

**Comment by Borda** [comment]
FYI: running the CI on the fork, ref: https://github.com/Lightning-Sandbox/gammatone/pull/1

**Comment by Borda** [comment]
@detly could you pls have a look/review? :rabbit:

**Comment by Borda** [comment]
> @detly could you pls have a look/review? 🐰

mind have a look, when you have time 🦩

**Comment by detly** [comment]
I'm not working on this any more, sorry. You should continue this in a fork so you have more control over the development. I don't mind being pinged for questions about the original code, but I won't have time for anything beyond that.

**Comment by Borda** [comment]
sure, we have already continued in a fork... and released your [package on PyPI](https://pypi.org/project/Gammatone/) (I am happy to add you there as owner if you share your user name for PyPI)
maybe would make sense, to consider archiving this repo so any user would be easier understand it is not actively maintained any more... 🦩

**Comment by detly** [comment]
> (I am happy to add you there as owner if you share your user name for PyPI)

No, that's okay, it's better not to create the expectation that I'm working on it.

>  maybe would make sense, to consider archiving this repo so any user would be easier understand it is not actively maintained any more... 🦩

I actually thought I had! I'll do that now there's a fork.

**Pull request closed without merging**
